sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install flake8
  - pip install hint
  - python setup.py install
install:
  - sleep 3
script: flake8 && hint .